version: '3.8'

networks:
  ingestor: {}

services:
  ingestor:
    image: jeffail/benthos
    volumes: 
    - /tmp:/tmp
    - ./file.csv:/tmp/data.csv
    - ./benthos.yaml:/benthos.yaml
    ports:
    - 4195:4195
    - 4190:4190
    networks:
    - ingestor
